### ISSUE TITLE
Is two licenses intended?

### ISSUE THREAD

**Issue by zkxs** [kazu0617/NeosLNLRelayDisabler#3]
The project currently has two different licenses: [LICENSE](https://github.com/kazu0617/NeosLNLRelayDisabler/blob/533692fce1acdb9bd13315e02f77afc953a0e7f2/LICENSE) and [license.txt](https://github.com/kazu0617/NeosLNLRelayDisabler/blob/533692fce1acdb9bd13315e02f77afc953a0e7f2/license.txt). Is this intentional?

**Comment by kazu0617** [comment]
I'lll set MIT license only, so i'll change it.

**Comment by kazu0617** [comment]
i changed.
